site_name: 全民瘋AI系列 [深度強化學習]
site_author: 10程式中
site_url: https://andy6804tw.github.io/crazyai-rl/
extra_css:
  - 'stylesheets/extra.css'
  - https://unpkg.com/katex@0/dist/katex.min.css
extra_javascript:
  - javascripts/extra.js
  - javascripts/analytics.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
theme:
  # logo: assets/logo.png
  name: material
  language: 'zh-TW'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    primary: 'teal'
    accent: 'teal'
  features:
    - content.footnote.tooltips
repo_url: https://github.com/andy6804tw/crazyai-rl
# use_directory_urls: false
edit_uri: ""
# Copyright
copyright: 'Copyright © 2018 - 2024 10程式中'
nav:
  - '基礎概念':
    - '1.什麼是強化學習.md'
    - '2.強化學習方法總覽.md'
  - '演算法/方法':
    - '3.1Q Leaning 概念.md'
    - '3.2Q Learning 範例一.md'
    - '4.DQN.md'
    - 'Policy Gradient.md'



markdown_extensions:
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: false
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  
  
# plugins:
#   - search
#   - mkpdfs:
#       design: design/report.css
#       author: Tsai Yi Lin
#       # company: "10程式中"
#       toc_title: Table of contents
#       output_path: pdf/全民瘋AI系列_深度強化學習_v1.0.pdf
